[package]
name = "elfo-macros"
version = "0.1.13"
description = "Macros for matching and deriving messages"
authors = ["Paul Loyd <pavelko95@gmail.com>"]
edition = "2018"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.60", features = ["parsing", "printing"] }
elfo-macros-impl = { path = "../elfo-macros-impl", version = "0.1.0" }
