[package]
name = "elfo-macros"
version = "0.1.0"
authors = ["Paul Loyd <pavelko95@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
quote = "1.0.9"
syn = { version = "1.0.60", features = ["full", "extra-traits"] }
