[workspace]
members = [
    "elfo",
    "elfo-core",
    "elfo-utils",
    "elfo-macros",
    "elfo-macros-impl",
    "elfo-test",
    "elfo-configurer",
    "elfo-logger",
    "elfo-dumper",
    "elfo-telemeter",
    "elfo-pinger",
    "examples",
]
