[workspace]
resolver = "2"
members = [
    "elfo",
    "elfo-core",
    "elfo-utils",
    "elfo-macros",
    "elfo-macros-impl",
    "elfo-test",
    "elfo-configurer",
    "elfo-logger",
    "elfo-dumper",
    "elfo-telemeter",
    "elfo-pinger",
    "elfo-network",

    "examples",
    "benches",
]

[workspace.package]
repository = "https://github.com/elfo-rs/elfo"
authors = ["Paul Loyd <pavelko95@gmail.com>"]
license = "MIT"
edition = "2021"
readme = "README.md"

[profile.release]
debug = 1

[patch.crates-io]
sharded-slab = { git = "https://github.com/loyd/sharded-slab", branch = "main" }
