[system.telemeters]
sink = "OpenMetrics"
address = "0.0.0.0:9100"

[system.dumpers]
path = "example.alice.{class}.dump"

[system.network]
# TCP
listen = ["tcp://127.0.0.1:9200"]
discovery.predefined = ["tcp://localhost:9201"]

# UDS (unix only)
#listen = ["uds://example-alice.socket"]
#discovery.predefined = ["uds://example-bob.socket"]
