[package]
name = "elfo-pinger"
version = "0.1.2"
description = "Pings groups of the elfo system"

authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
elfo-macros = { version = "0.1.15", path = "../elfo-macros" }
elfo-core = { version = "0.1.35", path = "../elfo-core", features = ["unstable"] }
elfo-utils = { version = "0.2.1", path = "../elfo-utils" }

tokio = { version = "1", features = ["time"] }
serde = { version = "1.0.120", features = ["derive"] }
humantime-serde = "1"
tracing = "0.1.25"
