[package]
name = "elfo-telemeter"
version = "0.2.0-alpha.13"
description = "Collects and exposes metrics of the elfo system"
keywords = ["elfo", "actor", "distributed", "tokio"]

repository.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true

[features]
unstable = []

[dependencies]
elfo-core = { version = "0.2.0-alpha.13", path = "../elfo-core", features = ["unstable"] } # TODO: do not need

tokio = "1"
hyper = { version = "1.0.1", features = ["server", "http1"] }
hyper-util = { version = "0.1.1", features = ["tokio"] }
pin-project-lite = "0.2"
serde = { version = "1.0.120", features = ["derive"] }
metrics = "0.17"
metrics-util = "0.10"
tracing = "0.1.25"
parking_lot = "0.12"
fxhash = "0.2.1"
humantime-serde = "1"
cow-utils = "0.1.2"
stability = "0.1.1"
