[package]
name = "elfo-utils"
version = "0.2.0"
description = "Utils"

authors.workspace = true
license.workspace = true
edition.workspace = true

[[bench]]
name = "rate_limiter"
harness = false

[dependencies]
derive_more = "0.99.11"
quanta = "0.10"

[dev-dependencies]
criterion = "0.4"
