[package]
name = "elfo-utils"
version = "0.1.1"
description = "Utils"
authors = ["Paul Loyd <pavelko95@gmail.com>"]
edition = "2018"
license = "MIT"

[[bench]]
name = "rate_limiter"
harness = false

[dependencies]
derive_more = "0.99.11"
quanta = "0.9.2"

[dev-dependencies]
anyhow = "1.0.40"
criterion = "0.3.4"
