[system.telemeters]
sink = "OpenMetrics"
address = "0.0.0.0:9101"

[system.dumpers]
path = "example.bob.{class}.dump"

[system.network]
# TCP
listen = ["tcp://127.0.0.1:9201"]
discovery.predefined = ["tcp://127.0.0.1:9200"]

# UDS (unix only)
#listen = ["uds://example-bob.socket"]
#discovery.predefined = ["uds://example-alice.socket"]
