[system.loggers]
#sink = "File"
#path = "example.log"

#format.with_location = false # default
#format.with_module = false   # default

[system.telemeters]
sink = "Prometheus"
address = "0.0.0.0:9042"

[system.dumpers]
path = "example.dump"

[producers]
# system.dumping.disabled = false # default
# system.telemetry.per_actor_group = true # default
# system.telemetry.per_actor_key = false # default

group_count = 3
item_count = 10

[reporters]
interval = "2s"
