[system.loggers]
# sink = "File"  # "Stdout" by default
# path = "example.log"
# format.with_location = false
# format.with_module = false

[system.telemeters]
sink = "Prometheus"
address = "0.0.0.0:9042"
# global_labels = [["label", "value"]]
# quantiles = [0.5, 0.75, 0.9, 0.95, 0.99]

[system.dumpers]
path = "example.dump"

[producers]
# system.logging.max_level = "Info" # default, one of: Trace, Debug, Info, Warn, Error, Off.
# system.logging.max_rate = 1000 # default
# system.dumping.disabled = false # default
# system.telemetry.per_actor_group = true # default
# system.telemetry.per_actor_key = false # default

group_count = 3
item_count = 10

[reporters]
interval = "2s"
