[package]
name = "elfo-test"
version = "0.1.19"
description = "Test utils"
authors = ["Paul Loyd <pavelko95@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
elfo-macros = { version = "0.1.14", path = "../elfo-macros" }
elfo-core = { version = "0.1.33", path = "../elfo-core", features = ["test-util"] }
elfo-configurer = { version = "0.1", path = "../elfo-configurer" }

tokio = "1"
serde = { version = "1.0.120", features = ["derive", "rc"] }
serde-value = "0.7.0"
futures-intrusive = "0.5"
futures = "0.3.12"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
once_cell = { version = "1.8.0" }
